// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.alarm_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_alarm_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_alarm_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "alarm_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}




































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "alarm_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_alarm_core_fn_func_load_work_schedules_ffi(`dbPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_alarm_core_fn_func_resolve_timezone_alarm_ffi(`inputTime`: RustBuffer.ByValue,`referenceDate`: RustBuffer.ByValue,`sourceTzName`: RustBuffer.ByValue,`deviceTzName`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_alarm_core_fn_func_save_work_schedule_ffi(`dbPath`: RustBuffer.ByValue,`schedule`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_alarm_core_fn_func_toggle_instance(`instances`: RustBuffer.ByValue,`instanceId`: RustBuffer.ByValue,`active`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_alarm_core_fn_func_toggle_month(`instances`: RustBuffer.ByValue,`year`: Int,`month`: Int,`scheduleId`: RustBuffer.ByValue,`active`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_alarm_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_alarm_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_alarm_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_alarm_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_alarm_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_alarm_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_alarm_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_alarm_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_alarm_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_alarm_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_alarm_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_alarm_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_alarm_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_alarm_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_alarm_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_alarm_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_alarm_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_alarm_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_alarm_core_checksum_func_load_work_schedules_ffi(
    ): Short
    fun uniffi_alarm_core_checksum_func_resolve_timezone_alarm_ffi(
    ): Short
    fun uniffi_alarm_core_checksum_func_save_work_schedule_ffi(
    ): Short
    fun uniffi_alarm_core_checksum_func_toggle_instance(
    ): Short
    fun uniffi_alarm_core_checksum_func_toggle_month(
    ): Short
    fun ffi_alarm_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_alarm_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_alarm_core_checksum_func_load_work_schedules_ffi() != 49504.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_alarm_core_checksum_func_resolve_timezone_alarm_ffi() != 9939.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_alarm_core_checksum_func_save_work_schedule_ffi() != 30008.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_alarm_core_checksum_func_toggle_instance() != 34289.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_alarm_core_checksum_func_toggle_month() != 12460.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



/**
 * Конкретный будильник на конкретную дату — то, что реально видно
 * в календаре и что реально сработает (или не сработает, если Skipped).
 */
data class AlarmInstance (
    var `id`: Uuid, 
    var `scheduleId`: Uuid, 
    var `date`: NaiveDate, 
    var `timeLocal`: NaiveTime, 
    var `status`: InstanceStatus, 
    var `origin`: AlarmOrigin
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAlarmInstance: FfiConverterRustBuffer<AlarmInstance> {
    override fun read(buf: ByteBuffer): AlarmInstance {
        return AlarmInstance(
            FfiConverterTypeUuid.read(buf),
            FfiConverterTypeUuid.read(buf),
            FfiConverterTypeNaiveDate.read(buf),
            FfiConverterTypeNaiveTime.read(buf),
            FfiConverterTypeInstanceStatus.read(buf),
            FfiConverterTypeAlarmOrigin.read(buf),
        )
    }

    override fun allocationSize(value: AlarmInstance) = (
            FfiConverterTypeUuid.allocationSize(value.`id`) +
            FfiConverterTypeUuid.allocationSize(value.`scheduleId`) +
            FfiConverterTypeNaiveDate.allocationSize(value.`date`) +
            FfiConverterTypeNaiveTime.allocationSize(value.`timeLocal`) +
            FfiConverterTypeInstanceStatus.allocationSize(value.`status`) +
            FfiConverterTypeAlarmOrigin.allocationSize(value.`origin`)
    )

    override fun write(value: AlarmInstance, buf: ByteBuffer) {
            FfiConverterTypeUuid.write(value.`id`, buf)
            FfiConverterTypeUuid.write(value.`scheduleId`, buf)
            FfiConverterTypeNaiveDate.write(value.`date`, buf)
            FfiConverterTypeNaiveTime.write(value.`timeLocal`, buf)
            FfiConverterTypeInstanceStatus.write(value.`status`, buf)
            FfiConverterTypeAlarmOrigin.write(value.`origin`, buf)
    }
}



/**
 * Правило будильника внутри графика — может быть несколько на одну смену
 * (например: "за 2 часа до смены" + "за 30 минут до смены").
 */
data class AlarmRule (
    var `id`: Uuid, 
    var `offsetMinutes`: kotlin.Int, 
    var `ringtoneId`: kotlin.String, 
    var `vibration`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAlarmRule: FfiConverterRustBuffer<AlarmRule> {
    override fun read(buf: ByteBuffer): AlarmRule {
        return AlarmRule(
            FfiConverterTypeUuid.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: AlarmRule) = (
            FfiConverterTypeUuid.allocationSize(value.`id`) +
            FfiConverterInt.allocationSize(value.`offsetMinutes`) +
            FfiConverterString.allocationSize(value.`ringtoneId`) +
            FfiConverterBoolean.allocationSize(value.`vibration`)
    )

    override fun write(value: AlarmRule, buf: ByteBuffer) {
            FfiConverterTypeUuid.write(value.`id`, buf)
            FfiConverterInt.write(value.`offsetMinutes`, buf)
            FfiConverterString.write(value.`ringtoneId`, buf)
            FfiConverterBoolean.write(value.`vibration`, buf)
    }
}



/**
 * Сам график работы — центральная сущность приложения.
 */
data class WorkSchedule (
    var `id`: Uuid, 
    var `name`: kotlin.String, 
    var `color`: kotlin.String, 
    var `pattern`: SchedulePattern, 
    var `source`: ScheduleSource, 
    var `startDate`: NaiveDate, 
    var `shiftStartTime`: NaiveTime, 
    var `alarms`: List<AlarmRule>, 
    var `isActive`: kotlin.Boolean, 
    var `isPaused`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWorkSchedule: FfiConverterRustBuffer<WorkSchedule> {
    override fun read(buf: ByteBuffer): WorkSchedule {
        return WorkSchedule(
            FfiConverterTypeUuid.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeSchedulePattern.read(buf),
            FfiConverterTypeScheduleSource.read(buf),
            FfiConverterTypeNaiveDate.read(buf),
            FfiConverterTypeNaiveTime.read(buf),
            FfiConverterSequenceTypeAlarmRule.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: WorkSchedule) = (
            FfiConverterTypeUuid.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`color`) +
            FfiConverterTypeSchedulePattern.allocationSize(value.`pattern`) +
            FfiConverterTypeScheduleSource.allocationSize(value.`source`) +
            FfiConverterTypeNaiveDate.allocationSize(value.`startDate`) +
            FfiConverterTypeNaiveTime.allocationSize(value.`shiftStartTime`) +
            FfiConverterSequenceTypeAlarmRule.allocationSize(value.`alarms`) +
            FfiConverterBoolean.allocationSize(value.`isActive`) +
            FfiConverterBoolean.allocationSize(value.`isPaused`)
    )

    override fun write(value: WorkSchedule, buf: ByteBuffer) {
            FfiConverterTypeUuid.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`color`, buf)
            FfiConverterTypeSchedulePattern.write(value.`pattern`, buf)
            FfiConverterTypeScheduleSource.write(value.`source`, buf)
            FfiConverterTypeNaiveDate.write(value.`startDate`, buf)
            FfiConverterTypeNaiveTime.write(value.`shiftStartTime`, buf)
            FfiConverterSequenceTypeAlarmRule.write(value.`alarms`, buf)
            FfiConverterBoolean.write(value.`isActive`, buf)
            FfiConverterBoolean.write(value.`isPaused`, buf)
    }
}





/**
 * Ошибки, которые могут вернуть FFI-функции ядра. Отдельный enum вместо
 * голого String — потому что uniffi умеет превращать error-enum в настоящее
 * исключение на стороне Kotlin, а строку — нет (её пришлось бы парсить руками).
 */
sealed class AlarmCoreException: kotlin.Exception() {
    
    class InstanceNotFound(
        
        val `id`: kotlin.String
        ) : AlarmCoreException() {
        override val message
            get() = "id=${ `id` }"
    }
    
    class DatabaseException(
        
        val `details`: kotlin.String
        ) : AlarmCoreException() {
        override val message
            get() = "details=${ `details` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<AlarmCoreException> {
        override fun lift(error_buf: RustBuffer.ByValue): AlarmCoreException = FfiConverterTypeAlarmCoreError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeAlarmCoreError : FfiConverterRustBuffer<AlarmCoreException> {
    override fun read(buf: ByteBuffer): AlarmCoreException {
        

        return when(buf.getInt()) {
            1 -> AlarmCoreException.InstanceNotFound(
                FfiConverterString.read(buf),
                )
            2 -> AlarmCoreException.DatabaseException(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: AlarmCoreException): ULong {
        return when(value) {
            is AlarmCoreException.InstanceNotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`id`)
            )
            is AlarmCoreException.DatabaseException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
        }
    }

    override fun write(value: AlarmCoreException, buf: ByteBuffer) {
        when(value) {
            is AlarmCoreException.InstanceNotFound -> {
                buf.putInt(1)
                FfiConverterString.write(value.`id`, buf)
                Unit
            }
            is AlarmCoreException.DatabaseException -> {
                buf.putInt(2)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}



/**
 * Откуда взялся этот конкретный будильник — из обычного паттерна графика,
 * вручную переопределён пользователем, или это timezone-будильник (п.4.2).
 */

enum class AlarmOrigin {
    
    FROM_PATTERN,
    MANUAL_OVERRIDE,
    TIMEZONE_MEETING;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAlarmOrigin: FfiConverterRustBuffer<AlarmOrigin> {
    override fun read(buf: ByteBuffer) = try {
        AlarmOrigin.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AlarmOrigin) = 4UL

    override fun write(value: AlarmOrigin, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Тип дня в графике — рабочий, выходной или ночная смена.
 * Нужен и для кастомных графиков (Custom(Vec<DayType>)), и для
 * отображения в календаре (какой цвет/иконку показать на конкретный день).
 */

enum class DayType {
    
    WORK,
    REST,
    NIGHT_SHIFT;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeDayType: FfiConverterRustBuffer<DayType> {
    override fun read(buf: ByteBuffer) = try {
        DayType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: DayType) = 4UL

    override fun write(value: DayType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Статус конкретного экземпляра будильника на конкретную дату.
 * Разница Active/SkippedByUser — это и есть механика "отключить,
 * но не удалить", которую ты просил в самом начале.
 */

enum class InstanceStatus {
    
    ACTIVE,
    SKIPPED_BY_USER,
    FIRED,
    MISSED;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeInstanceStatus: FfiConverterRustBuffer<InstanceStatus> {
    override fun read(buf: ByteBuffer) = try {
        InstanceStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: InstanceStatus) = 4UL

    override fun write(value: InstanceStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Паттерн графика — три принципиально разных способа задать расписание.
 * Это как раз то, что различает пресет 2/2 от кастомного графика
 * от "рандомного по приколу" (п.4.1 ТЗ).
 */
sealed class SchedulePattern {
    
    data class Cyclic(
        val `workDays`: kotlin.UByte, 
        val `restDays`: kotlin.UByte) : SchedulePattern() {
        companion object
    }
    
    data class Custom(
        val v1: List<DayType>) : SchedulePattern() {
        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSchedulePattern : FfiConverterRustBuffer<SchedulePattern>{
    override fun read(buf: ByteBuffer): SchedulePattern {
        return when(buf.getInt()) {
            1 -> SchedulePattern.Cyclic(
                FfiConverterUByte.read(buf),
                FfiConverterUByte.read(buf),
                )
            2 -> SchedulePattern.Custom(
                FfiConverterSequenceTypeDayType.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: SchedulePattern) = when(value) {
        is SchedulePattern.Cyclic -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterUByte.allocationSize(value.`workDays`)
                + FfiConverterUByte.allocationSize(value.`restDays`)
            )
        }
        is SchedulePattern.Custom -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeDayType.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: SchedulePattern, buf: ByteBuffer) {
        when(value) {
            is SchedulePattern.Cyclic -> {
                buf.putInt(1)
                FfiConverterUByte.write(value.`workDays`, buf)
                FfiConverterUByte.write(value.`restDays`, buf)
                Unit
            }
            is SchedulePattern.Custom -> {
                buf.putInt(2)
                FfiConverterSequenceTypeDayType.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





/**
 * Источник графика — чтобы отличать "взял готовый пресет 2/2"
 * от "накидал свой график руками" (п.4.1 ТЗ, визуальные бейджи).
 */
sealed class ScheduleSource {
    
    data class Preset(
        val v1: kotlin.String) : ScheduleSource() {
        companion object
    }
    
    object Custom : ScheduleSource()
    
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeScheduleSource : FfiConverterRustBuffer<ScheduleSource>{
    override fun read(buf: ByteBuffer): ScheduleSource {
        return when(buf.getInt()) {
            1 -> ScheduleSource.Preset(
                FfiConverterString.read(buf),
                )
            2 -> ScheduleSource.Custom
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ScheduleSource) = when(value) {
        is ScheduleSource.Preset -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
        is ScheduleSource.Custom -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
    }

    override fun write(value: ScheduleSource, buf: ByteBuffer) {
        when(value) {
            is ScheduleSource.Preset -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is ScheduleSource.Custom -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalTypeUuid: FfiConverterRustBuffer<Uuid?> {
    override fun read(buf: ByteBuffer): Uuid? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeUuid.read(buf)
    }

    override fun allocationSize(value: Uuid?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeUuid.allocationSize(value)
        }
    }

    override fun write(value: Uuid?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeUuid.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeAlarmInstance: FfiConverterRustBuffer<List<AlarmInstance>> {
    override fun read(buf: ByteBuffer): List<AlarmInstance> {
        val len = buf.getInt()
        return List<AlarmInstance>(len) {
            FfiConverterTypeAlarmInstance.read(buf)
        }
    }

    override fun allocationSize(value: List<AlarmInstance>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeAlarmInstance.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<AlarmInstance>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeAlarmInstance.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeAlarmRule: FfiConverterRustBuffer<List<AlarmRule>> {
    override fun read(buf: ByteBuffer): List<AlarmRule> {
        val len = buf.getInt()
        return List<AlarmRule>(len) {
            FfiConverterTypeAlarmRule.read(buf)
        }
    }

    override fun allocationSize(value: List<AlarmRule>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeAlarmRule.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<AlarmRule>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeAlarmRule.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeWorkSchedule: FfiConverterRustBuffer<List<WorkSchedule>> {
    override fun read(buf: ByteBuffer): List<WorkSchedule> {
        val len = buf.getInt()
        return List<WorkSchedule>(len) {
            FfiConverterTypeWorkSchedule.read(buf)
        }
    }

    override fun allocationSize(value: List<WorkSchedule>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeWorkSchedule.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<WorkSchedule>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeWorkSchedule.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeDayType: FfiConverterRustBuffer<List<DayType>> {
    override fun read(buf: ByteBuffer): List<DayType> {
        val len = buf.getInt()
        return List<DayType>(len) {
            FfiConverterTypeDayType.read(buf)
        }
    }

    override fun allocationSize(value: List<DayType>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeDayType.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<DayType>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeDayType.write(it, buf)
        }
    }
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias NaiveDate = kotlin.String
public typealias FfiConverterTypeNaiveDate = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias NaiveTime = kotlin.String
public typealias FfiConverterTypeNaiveTime = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Uuid = kotlin.String
public typealias FfiConverterTypeUuid = FfiConverterString
        /**
         * FFI-обёртка: открывает БД, загружает все графики, закрывает соединение.
         */
    @Throws(AlarmCoreException::class) fun `loadWorkSchedulesFfi`(`dbPath`: kotlin.String): List<WorkSchedule> {
            return FfiConverterSequenceTypeWorkSchedule.lift(
    uniffiRustCallWithError(AlarmCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_alarm_core_fn_func_load_work_schedules_ffi(
        FfiConverterString.lower(`dbPath`),_status)
}
    )
    }
    

        /**
         * FFI-обёртка над resolve_timezone_alarm для вызова из Kotlin/RN.
         * Часовые пояса передаются как IANA-строки (например "Europe/Moscow",
         * "Asia/Yekaterinburg"), результат возвращается в формате "HH:MM".
         */ fun `resolveTimezoneAlarmFfi`(`inputTime`: NaiveTime, `referenceDate`: NaiveDate, `sourceTzName`: kotlin.String, `deviceTzName`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_alarm_core_fn_func_resolve_timezone_alarm_ffi(
        FfiConverterTypeNaiveTime.lower(`inputTime`),FfiConverterTypeNaiveDate.lower(`referenceDate`),FfiConverterString.lower(`sourceTzName`),FfiConverterString.lower(`deviceTzName`),_status)
}
    )
    }
    

        /**
         * FFI-обёртка: открывает БД по пути, сохраняет график, закрывает соединение.
         * Мобильная сторона не должна управлять нативным Connection через границу FFI —
         * поэтому вся работа с файлом происходит внутри одного вызова.
         */
    @Throws(AlarmCoreException::class) fun `saveWorkScheduleFfi`(`dbPath`: kotlin.String, `schedule`: WorkSchedule)
        = 
    uniffiRustCallWithError(AlarmCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_alarm_core_fn_func_save_work_schedule_ffi(
        FfiConverterString.lower(`dbPath`),FfiConverterTypeWorkSchedule.lower(`schedule`),_status)
}
    
    

        /**
         * Переключает статус конкретного будильника: Active <-> SkippedByUser.
         * Принимает список инстансов и возвращает НОВЫЙ список с обновлённым
         * статусом — FFI-граница всегда копирует данные, "изменить на месте
         * по ссылке" через неё невозможно (Kotlin/RN не имеют доступа к памяти Rust).
         */
    @Throws(AlarmCoreException::class) fun `toggleInstance`(`instances`: List<AlarmInstance>, `instanceId`: Uuid, `active`: kotlin.Boolean): List<AlarmInstance> {
            return FfiConverterSequenceTypeAlarmInstance.lift(
    uniffiRustCallWithError(AlarmCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_alarm_core_fn_func_toggle_instance(
        FfiConverterSequenceTypeAlarmInstance.lower(`instances`),FfiConverterTypeUuid.lower(`instanceId`),FfiConverterBoolean.lower(`active`),_status)
}
    )
    }
    

        /**
         * Массово переключает статус всех будильников за указанный месяц/год.
         * Возвращает обновлённый список инстансов целиком (см. toggle_instance
         * про то, почему не &mut).
         */ fun `toggleMonth`(`instances`: List<AlarmInstance>, `year`: kotlin.Int, `month`: kotlin.UInt, `scheduleId`: Uuid?, `active`: kotlin.Boolean): List<AlarmInstance> {
            return FfiConverterSequenceTypeAlarmInstance.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_alarm_core_fn_func_toggle_month(
        FfiConverterSequenceTypeAlarmInstance.lower(`instances`),FfiConverterInt.lower(`year`),FfiConverterUInt.lower(`month`),FfiConverterOptionalTypeUuid.lower(`scheduleId`),FfiConverterBoolean.lower(`active`),_status)
}
    )
    }
    


